#!/usr/bin/env bash

cd spring-music-repo
apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists

curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar -zx
./cf --version
